---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "${MOLECULE_DOCKER_IMAGE:-geerlingguy/docker-ubuntu2004-ansible:latest}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  inventory:
    group_vars:
      all:
        git_lfs: 'yes'
        git_configure: 'yes'
scenario:
  name: default
verifier:
  name: testinfra
